In [2]:
import numpy as np
import pandas as pd

1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [19]:
x=np.arange(0,1000,1)

print(f'La matriz x de tamaño {len(x)} ocupa {x.nbytes} bytes de información.')

La matriz x de tamaño 1000 ocupa 4000 bytes de información.


2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla

In [22]:
x=np.arange(1000,-1,-2)
x[-10:]

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

3. Dado el array:

2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1 

Seleccione con una instrucción el subarray de elementos

0 3 7 4

Después, seleccione el subarray de elementos

2 5

8 5

In [49]:
x=[[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]]
a=np.array(x)

In [52]:
a[::2,::2]


array([[2, 5],
       [8, 5]])

4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).


In [60]:
a = [1, 4, 2, 7] 
b = [1, 3, 2, 9]

a=np.array(a)
b=np.array(b)

np.mean(a-b)

-0.25

5. Tengo valores de cordenadas (x, y) en las columnas del array 

1.33    4.5

30.0    10.7

70.2    0.5

Agregue a este array las coordenadas (37.1, -3.6). 
Muestre en pantalla las dimensiones del nuevo 
array.

In [12]:
y= np.array([[1.33, 4.5],[30.0,10.7],[70.2,0.5]])
y=np.append(y,[[37.1, -3.6]],axis=0)
y

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

6. Copie el array del ejercicio anterior. Traspóngalo Agregue ahora dos nuevos pares de coordenadas: (10.8, 3.0) y (35.8, 12.0).

In [16]:
yt=

<function ndarray.transpose>